import { Open_Sans } from "@next/font/google";
import Link from "next/link";
import styles from "./rootStyle.module.css";
import "./globals.css";

const openSans = Open_Sans({
  subsets: ["latin"],
  weight: ["400"]
});

export default function ConferenceLayout({ children }) {
  return (
    <html lang="en" className={openSans.className}>
      <head />
      <body>
        <header>
          <h2>
            <Link href="/home" className={styles.homeLink}>Home</Link>
          </h2>       
          <h2>
            <Link href="/blog" className={styles.menuBarLink}>Blog</Link>
          </h2>
          <h2>
            <Link href="/conference" className={styles.menuBarLink}>Conference</Link>
          </h2>
          <h2>
            <Link href="/settings" className={styles.menuBarLink}>Settings</Link>
          </h2>
        </header>
        {children}
      </body>
    </html>
  );
}

// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }
